apiVersion: v1
kind: Service
metadata:
  name: {{ include "kie.fullname" . }}
  namespace: {{ include "kie.namespace" . }}
  labels:
    {{- include "kie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: metrics
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "kie.selectorLabels" . | nindent 4 }}
