---
name: Lint (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
    - ".github/workflows/test.golang.yml"
    - ".github/workflows/lint.golang.yml"
    - "**.go"
    - "go.*"
  push:
    branches: [main]

jobs:
  golangci-lint:
    name: Golang CI lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: "go.mod"
    - uses: golangci/golangci-lint-action@d6238b002a20823d52840fda27e2d4891c5952dc # v4.0.1
      with:
        # renovate: datasource=github-releases depName=golangci/golangci-lint
        version: v1.57.2
