---
name: Lint (YAML)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
    - ".github/workflows/lint.yaml.yml"
    - "**.ya?ml"
  push:
    branches: [main]

jobs:
  yamllint:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # tag=v3.1.1
      with:
        format: github
