---
name: Lint (Github Actions workflows)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
    - ".github/workflows/lint.github-action.yml"
    - ".github/workflows/**"
  push:
    branches: [main]

jobs:
  github_action_lint:
    name: Github Action lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@ba37328d4ea95eaf8b3bd6c6cef308f709a5f2ec # v3.0.3
