---
name: Test (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
    - ".github/workflows/test.golang.yml"
    - ".github/workflows/lint.golang.yml"
    - "**.go"
    - "go.*"
  push:
    branches: [main]

jobs:
  go-test:
    name: Golang test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: "go.mod"
    - name: Run golang tests
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Archive code coverage results
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: golang-coverage-report
        path: coverage.out
        retention-days: 1

  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    needs: [go-test]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
      with:
        name: golang-coverage-report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
      with:
        slug: Thibaut-gauvin/kie
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        fail_ci_if_error: true
