---
name: Test (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
    - ".github/workflows/test.golang.yml"
    - ".github/workflows/lint.golang.yml"
    - "**.go"
    - "go.*"
  push:
    branches: [main]

jobs:
  go-test:
    name: Golang test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: "go.mod"
    - name: Run golang tests
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Archive code coverage results
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: golang-coverage-report
        path: coverage.out
        retention-days: 1

  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    needs: [go-test]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
      with:
        name: golang-coverage-report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@c16abc29c95fcf9174b58eb7e1abf4c866893bc8 # v4.1.1
      with:
        slug: Thibaut-gauvin/kie
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        fail_ci_if_error: true
